version: '2.4'

services:
  fluentd:
    build: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - task-network
  task-flow-api:
    build: ./docker/
    container_name: ${COMPOSE_PROJECT_NAME}-backend-dev
    volumes:
      - .:/usr/local/bin/
    ports:
      - "${PORT}:${PORT}" # api port
      - "${PORT_DEBUG}:2345" # debugger port
    networks:
      - task-network
    command: ["sh", "-c", "swag init && ./docker/debug.sh"]
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      fluentd:
        condition: service_started
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.task-rest-api-service
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - task-network
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: ${KAFKA_HOST}
    restart: always
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ENABLE_KRAFT: "false"
    networks:
      - task-network
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
    image: elasticsearch:7.17.17
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for testing
    healthcheck:
      # Check whether service is ready
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "9200:9200"
    networks:
        - task-network
  kibana:
    image: kibana:7.17.17
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - task-network
networks:
  task-network:
    external: true
volumes:
  esdata:
    driver: local
