version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task-network

  task-storage-service:
    build: ./docker
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.task-storage-service
    container_name: task-storage-service
    volumes:
      - .:/usr/local/bin/
    ports:
      - "5436:50051"
    depends_on:
      - db
    networks:
      - task-network
    command: [ "CompileDaemon", "-command=go run main.go" ]

volumes:
  postgres-data:

networks:
  task-network:
    external: true